первая реализация
avalon-dev-j110/laboratornaya-rabota-no1-janeforjane pull request #1
Opened 2020-03-30 12:00 UTC by janeforjane

2020-04-02 05:57 UTC, KolosovKD requested changes

2020-04-02 05:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +    public String name;
поле должно быть private, если нет каких-то особых обстоятельств.

2020-04-02 05:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Passport.java
> +    public String lastName;
аналогично, лучше private

2020-04-02 05:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
> +        }
Формирование полного имени лучше перенести в класс Passport, а здесь оставить проверку что пасспорт заполнен и вызов его метода. Например,
if(passport != null) {
  return passport.getFullName();
} else {
  return "anonymous":
}

2020-04-02 05:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
> +        return address.getCity() + " " + address.getStreet() + " " + address.getHouseNumber() + " " + address.getFlatNumber();
здесь также лучше перенести это в класс Address.
Тогда если вдруг в какой-то момент поменяется формат представления адреса, то надо будет изменить только один класс.
А если разносить эту логику по приложению, то придется искать и менять все места формирования строки адреса.

2020-04-02 05:57 UTC, KolosovKD commented on src/ru/avalon/java/dev/j10/labs/Main.java
> +        ivanov.getPass().setName("Ivan");
Хорошее решение с сеттерами, но есть нюанс.
Если вы заполняете все поля прям в конструкторе, вы предполагаете что они обязательно будут заполнены. А в случае с сеттерами вы предполагаете, что поля могут быть заполнены, а могут и не быть. Тогда вам надо предусмотреть, чтобы если вдруг, например, отчество не заполнили, то не было в результате вот такого вывода:

Ivan null Ivanov

2020-04-10 18:43 UTC, janeforjane commented on src/ru/avalon/java/dev/j10/labs/models/Person.java
> +        return address.getCity() + " " + address.getStreet() + " " + address.getHouseNumber() + " " + address.getFlatNumber();
Кирилл, считаю что под адресом, в зависимости от задачи/логики может подразумеваться разное: для каких то целей - это улица+дом+квартира, для каких то - город + улица;

2020-04-14 20:46 UTC, KolosovKD commented
Принято, спасибо.

2020-04-14 20:46 UTC, merged